flight <- read.csv("hflights.csv")
str(flight)
summary(flight)
head(flight)
games <- read.csv("vgsales.csv")
str(games)
summary(games)
head(games)
climate <- read.csv("RAW_climate_data_20220809.csv")
str(climate)
summary(climate)
head(climate)
